### ISSUE TITLE
Custom build of KiCAD?

### ISSUE THREAD

**Issue by nicktramp** [gregdavill/cap-sense-flex#1]
I was trying to open these to have a look, but found my version of KiCAD (v5.1.10, Windows and Linux Mint) can't open it; I get an error message about needing a newer version. Viewing the pcbnew files in a text editor, I see the pcbnew version listed as 20200518 and the host string has the version 5.99. Anything created with the precompiled v5.1.10 gives a version of 20171130/5.1.10.

Did you use a version of KiCAD you had built to create these? If so, would you mind sharing any changes made (e.g. in a readme)?

**Comment by gregdavill** [comment]
These were built with the Nightly version of KiCad. 

You can download pre-compiled Nightlies for both Windows and Linux. They're installed separate from 5.1, so you can still go back and use 5.1 for other designs.

But once a design has been saved in the new v6 format then it can't be opened by v5.1, due to additions/changes to the file formats.

**Comment by nicktramp** [comment]
Got it. Thanks!
